spring.application.name=PhosphOps
spring.profiles.active=local

### DATABASE ###
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/phosphopsdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

### JPA / HIBERNATE ###
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

### SERVER ###
server.servlet.context-path=/PhosphOps
server.port=8087

### JWT ###
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000

### FRONTEND ###
app.frontend.url=${FRONTEND_URL:http://localhost:4200}

### GOOGLE OAUTH2 ###
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

### CLOUDINARY ###
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

### GEMINI AI ###
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent

logging.level.org.springframework.security=DEBUG
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:4201,http://localhost}
